### ISSUE TITLE
Division slugs need to be shorter

### ISSUE THREAD

**Issue by mwchen** [ashish-b10/tournament_manager#15]
Right now, the division and match slugs are too long because they include information about the particular tournament. As a result, everything is extremely long. We need to be succinct assuming that we already know which tournament is the one specified. 

For example, "Men's A (Tournament NAME - Tournament Date) " can be reduced to "Men's A" to make it simpler to read.

**Comment by ashish-b10** [comment]
The first task on this bug is to replace all implementations of **str** in models.py . Once this is done, the UI should still look the same (because when calling str(), if **str** is not implemented, Python will call **repr** instead).

Once that's done, we can implement a different **str** for any models that don't look nice in the interface. For example, for a TournamentDivision, str() should return "Men's A" and repr() should return "Men's A (cornell-2015-11-01")

**Comment by ashish-b10** [comment]
This is pretty much done now. Re-open if there are any that weren't caught
