### ISSUE TITLE
print new match sheets as tournament progresses

### ISSUE THREAD

**Issue by edavidaja** [ashish-b10/tournament_manager#32]
I don't know how much value there is to doing that in the short run if you're planning to have the whole thing run without printers anyway.

**Comment by ashish-b10** [comment]
This is already supported, but we can't use it right now because nobody is updating matches in our database as the day goes on. This probably won't change until we have computer monitors at the rings updating the results of matches in our database. But if you think about it, if we reach this point, we probably won't need match sheets at all....

In any case, since we can already do this, I'm going to close the issue.
