### ISSUE TITLE
delete tournament modal not working properly

### ISSUE THREAD

**Issue by mwchen** [ashish-b10/tournament_manager#6]
does not properly show which tournament is the one being deleted.

**Comment by ashish-b10** [comment]
The problem was that there was one &lt;div class="modal" id="confirmDeleteTournamentModal"...&gt; element was being created for each tournament on the page, so when clicking any Delete button (&lt;button type="button" data-target="#confirmDeleteTournamentModal"&gt;, there were multiple elements with `id="confirmDeleteTournamentModal"` to choose from.

I fixed it by hacking the modal id and the button data-target to use a unique identifier for each tournament.

**Comment by ashish-b10** [comment]
Commit ab045958a5a1e79668bb540d19e4290408e96af8 fixes this
